import math
import networkx as nx
import itertools
import logging
import os


from nopywer.analyze import _compute_distro_requirements
from nopywer.constants import EXTRA_CABLE_LENGTH_M, PF, RHO_COPPER, V0, VDROP_THRESHOLD_PERCENT
from nopywer.geometry import geodesic_distance_m
from nopywer.models import _CABLE_TYPES, Cable, PowerGrid
from nopywer.optimization_tools import assign_phases_from_grid
from nopywer.optimize import _compute_power_flow

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
    datefmt="%m-%d %H:%M",
    filename="optimizer.log",
    filemode="w",
)
console = logging.StreamHandler()
console.setLevel(logging.INFO)
formatter = logging.Formatter("%(name)-12s: %(levelname)-8s %(message)s")
console.setFormatter(formatter)
logging.getLogger().addHandler(console)


MAX_POWER = 100000
RADIUS_M = 50  # tune this: typical cluster radius in your layout

INVENTORY = os.getenv("NOPYWER_INVENTORY", "orange_inventory.xlsx")

# basically, for any grid generated by the optim algo:
# you need to compute the voltage drop, current in each cables etc.
# So phases need to be assigned first. Then you check if the grid is valid
# then, only for those feasible solutions, you try to optimize voltage drop, total length, etc

def optimize_layout(grid: PowerGrid, extra_cable_m=EXTRA_CABLE_LENGTH_M, 
                    hub_discount=0.7, radiality_factor=0.3) -> PowerGrid: 
    # 0 = no discount, 1 = free connection to perfect hub
    # Radiality factor: penalizes edges between non-generator nodes
    # Higher RADIALITY_FACTOR = more star-shaped (all connect to generator)
    # Lower RADIALITY_FACTOR = more chained (MST-like)

    nodes = grid.nodes
    node_names = list(nodes.keys())
    generator = next(n for n, node in nodes.items() if node.is_generator)
    vdrop = None
    
    G = nx.Graph()
    max_section = max(tier.area_mm2 for tier in _CABLE_TYPES)
    
    dist_matrix = {}
    define_distance_matrix(nodes, node_names, dist_matrix)
    
    # Precompute hub score for each node:
    # how much load is reachable within a radius from this node
    hub_score = precompute_hub(nodes, node_names, dist_matrix)
        
    max_hub = max(hub_score.values()) if hub_score else 1
    generator_position = (nodes[generator].lon, nodes[generator].lat)

    logger.info(f"[HUB] scores: {sorted(hub_score.items(), key=lambda x: x[1], reverse=True)[:5]}")
    for i, j in itertools.combinations(node_names, 2):
        d = dist_matrix[(i, j)]
        base_weight = RHO_COPPER / max_section * d * d

        if nodes[i].is_generator or nodes[j].is_generator:
            hub_node = j if nodes[i].is_generator else i
            
            if is_distro(hub_node):
                # hub_discount: cuanto mayor, más barato conectar distros al generador
                weight = base_weight * (1 - hub_discount) * 0.1
            else:
                # radiality_factor: cuanto mayor, más caro conectar non-distro al generador
                weight = base_weight * (1 + radiality_factor * 10)
                
        elif is_distro(i) and is_distro(j):
            # distro↔distro: cheap only if closer to each other than to generator
            d_i_gen = dist_matrix[(i, generator)]
            d_j_gen = dist_matrix[(j, generator)]
            if d < min(d_i_gen, d_j_gen):
                weight = base_weight * (1 - hub_discount) * 0.1
            else:
                weight = base_weight * (1 + radiality_factor)
                
        elif is_distro(i) or is_distro(j):
            # non-distro↔distro: cheap
            weight = base_weight  * (1 - hub_discount * 0.8)

        else:
            # non-distro↔non-distro: expensive
            weight = base_weight * (1 + radiality_factor * 5)

        G.add_edge(i, j, weight=weight)
    
    mst = nx.minimum_spanning_tree(G, algorithm='kruskal')
    if generator not in mst:
        logger.warning("Generator %s is not present in MST nodes, using fallback root", generator)
        generator = next(i for i in mst.nodes if 'generator' in str(i).lower())
    
    oriented_tree = nx.bfs_tree(mst, source=generator)
    for node in oriented_tree.nodes:
        if not is_distro(node) or nodes[node].is_generator:
            continue
        parent = next(iter(oriented_tree.predecessors(node)), None)
        if parent and not nodes[parent].is_generator and not is_distro(parent):
            logger.warning(
                f"[DISTRO] {node} is connected to non-distro {parent} — "
                f"constraint not satisfied, increase distro↔non-distro penalty"
            )

    tiers = assign_tiers_to_nodes(oriented_tree, nodes, dist_matrix)
    
    # vdrop, warnings = compute_voltage_drop(oriented_tree, nodes, dist_matrix, tiers)

    # if warnings:
    #     oriented_tree = fix_voltage_drop_warnings(oriented_tree, nodes, dist_matrix, warnings, tiers)
    #     # Recompute tiers and vdrop after fix
    #     tiers = assign_tiers_to_nodes(oriented_tree, nodes)
    #     vdrop, warnings = compute_voltage_drop(oriented_tree, nodes, dist_matrix, tiers)
    #     if warnings:
    #         logger.warning(f"[VDROP] {len(warnings)} edges still exceed threshold after fix")

        
    cables = oriented_tree_to_grid(oriented_tree, dist_matrix,nodes, EXTRA_CABLE_LENGTH_M, vdrop=vdrop)
    logger.debug("Assigned tiers from MST: %s", tiers)
    
    computed_cables = _compute_power_flow(cables, grid.nodes)
    node_phase, cable_phase, phase_loads = assign_phases_from_grid(grid.nodes, computed_cables, logger)
    
    for n in node_names:
        nodes[n].phase = node_phase.get(n, 0)
        
    for cable in computed_cables:
        cable.phase = cable_phase.get((cable.from_node, cable.to_node), 0)

    grid = PowerGrid(
        nodes=nodes,
        cables={cable.id: cable for cable in computed_cables},
    )
    grid.phase_loads = phase_loads
    
    _compute_distro_requirements(grid)
    return grid

def fix_voltage_drop_warnings(
    oriented_tree: nx.DiGraph,
    nodes: dict,
    dist_matrix: dict,
    warnings: list,
    cable_tiers: dict,
) -> nx.DiGraph:
    """
    For each warning edge, try to find a closer parent for the child node.
    Returns a modified tree.
    """
    if not warnings:
        return oriented_tree

    tree = oriented_tree.copy()
    generator = next(n for n, node in nodes.items() if node.is_generator)
    node_names = list(nodes.keys())

    for w in warnings:
        node_i, node_j = w["edge"]
        logger.info(f"[VDROP FIX] Trying to re-route {node_i}→{node_j} ({w['vdrop_pct']}%)")

        # Find alternative parents: nodes already in tree, closer to node_j
        current_dist = dist_matrix[(node_i, node_j)]
        candidates = [
            n for n in node_names
            if n != node_j
            and n in tree.nodes
            and dist_matrix[(n, node_j)] < current_dist
            and not nx.has_path(tree, node_j, n)  # avoid cycles
        ]
        candidates.sort(key=lambda n: dist_matrix[(n, node_j)])

        for candidate in candidates:
            # Check if rerouting fixes the voltage drop
            new_flow = sum(
                nodes[n].power_watts
                for n in nx.descendants(tree, node_j) | {node_j}
            )
            new_d = dist_matrix[(candidate, node_j)]
            tier = cable_tiers.get((node_i, node_j))
            if tier:
                new_vdrop = 100 * (new_flow / (V0 * PF)) * (RHO_COPPER / tier.area_mm2) * new_d / V0
                if new_vdrop <= VDROP_THRESHOLD_PERCENT:
                    # Apply reroute
                    tree.remove_edge(node_i, node_j)
                    tree.add_edge(candidate, node_j)
                    logger.info(
                        f"[VDROP FIX] Re-routed {node_j}: "
                        f"{node_i}→{node_j} ({w['vdrop_pct']:.1f}%) "
                        f"replaced by {candidate}→{node_j} ({new_vdrop:.1f}%)"
                    )
                    break
        else:
            logger.warning(
                f"[VDROP FIX] No fix found for {node_i}→{node_j}, "
                f"consider upgrading cable tier or splitting the branch"
            )

    return tree

def compute_voltage_drop(
    oriented_tree: nx.DiGraph,
    nodes: dict,
    dist_matrix: dict,
    cable_tiers: dict,  # (from, to) → CableTier, resultado de assign_tiers_to_nodes
) -> dict:
    """Returns {(from, to): vdrop_percent} for each edge."""
    generator = next(n for n, node in nodes.items() if node.is_generator)

    # Compute cumulative flow (watts) for each edge = sum of all descendant loads
    cumulative_flow = {}
    for node_i, node_j in nx.bfs_edges(oriented_tree, source=generator):
        subtree_load = sum(
            nodes[n].power_watts
            for n in nx.descendants(oriented_tree, node_j) | {node_j}
            if not nodes[n].is_generator
        )
        cumulative_flow[(node_i, node_j)] = subtree_load

    # Compute voltage drop per edge
    vdrop = {}
    warnings = []
    for (node_i, node_j), flow_w in cumulative_flow.items():
        tier = cable_tiers.get((node_i, node_j))
        if tier is None:
            continue
        d = dist_matrix[(node_i, node_j)]
        resistance_total = (RHO_COPPER / tier.area_mm2) * d  # ohms
        current_a = flow_w / (V0 * PF)
        vdrop_v = current_a * resistance_total
        vdrop_pct = 100 * vdrop_v / V0

        vdrop[(node_i, node_j)] = vdrop_pct

        if vdrop_pct > VDROP_THRESHOLD_PERCENT:
            warnings.append({
                "edge": (node_i, node_j),
                "vdrop_pct": round(vdrop_pct, 2),
                "flow_w": round(flow_w),
                "tier": tier.area_mm2,
                "distance_m": round(d),
            })
            logger.warning(
                f"[VDROP] {node_i}→{node_j}: {vdrop_pct:.1f}% "
                f"(flow={flow_w:.0f}W, d={d:.0f}m, tier={tier.area_mm2}mm²)"
            )

    return vdrop, warnings

def is_distro(name: str) -> bool:
        return name.lower().startswith('distro')

def precompute_hub(nodes, node_names, dist_matrix):
    hub_score = {}
    for n in node_names:
        if nodes[n].is_generator:
            continue
        nearby_load = sum(
            nodes[m].power_watts
            for m in node_names
            if m != n and not nodes[m].is_generator
            and dist_matrix[(n, m)] <= RADIUS_M
        )
        hub_score[n] = nearby_load
    return hub_score

def oriented_tree_to_grid(
    oriented_tree: nx.DiGraph,
    dist_matrix: dict,
    nodes: dict,
    extra_cable_m: float = EXTRA_CABLE_LENGTH_M,
    vdrop =None,
) -> PowerGrid:
    
    cables = []
    for cid, (node_i, node_j) in enumerate(oriented_tree.edges()):
        d = dist_matrix[(node_i, node_j)]
        cable = Cable(
            id=f"opt_{cid}",
            from_node=node_i,
            to_node=node_j,
            length_m=d + extra_cable_m,
            from_coords=(nodes[node_i].lon, nodes[node_i].lat),
            to_coords=(nodes[node_j].lon, nodes[node_j].lat),
        )
        if vdrop:
            cable.vdrop_pct = round(vdrop.get((node_i, node_j), 0), 2)
            cable.vdrop_warning = cable.vdrop_pct > VDROP_THRESHOLD_PERCENT
        cables.append(cable)
    return cables

# def assign_tiers_to_nodes(tree, nodes, dist_matrix=None):
#     tiers = nx.single_source_shortest_path_length(tree, list(tree.nodes)[0])
#     for node_name, tier in tiers.items():
#         node = nodes.get(node_name)
#         if node is None:
#             continue
#         try:
#             node.tier = tier
#         except AttributeError:
#             pass
#     return tiers

def assign_tiers_to_nodes(
    tree: nx.DiGraph,
    nodes: dict,
    dist_matrix: dict,
) -> dict:
    """
    Assigns the minimum cable tier to each edge that satisfies:
    - current capacity >= cumulative flow
    - voltage drop <= threshold
    Returns {(from, to): CableTier}
    """
    generator = next(n for n, node in nodes.items() if node.is_generator)
    cable_tiers = {}

    for node_i, node_j in nx.bfs_edges(tree, source=generator):
        # Cumulative flow = sum of all descendant loads
        subtree_nodes = nx.descendants(tree, node_j) | {node_j}
        flow_w = sum(
            nodes[n].power_watts
            for n in subtree_nodes
            if not nodes[n].is_generator
        )
        current_a = flow_w / (V0 * PF)
        d = dist_matrix[(node_i, node_j)]

        # Select minimum tier that satisfies both constraints
        selected_tier = None
        for tier in sorted(_CABLE_TYPES, key=lambda t: t.area_mm2):  # smallest first
            # Capacity check
            if tier.max_current_a < current_a:
                continue
            # Voltage drop check
            resistance_total = (RHO_COPPER / tier.area_mm2) * d
            vdrop_pct = 100 * current_a * resistance_total / V0
            if vdrop_pct > VDROP_THRESHOLD_PERCENT:
                continue
            selected_tier = tier
            break

        if selected_tier is None:
            # No tier satisfies constraints — use largest available and warn
            selected_tier = max(_CABLE_TYPES, key=lambda t: t.area_mm2)
            logger.warning(
                f"[TIER] No suitable tier for {node_i}→{node_j}: "
                f"flow={flow_w:.0f}W, current={current_a:.1f}A, d={d:.0f}m — "
                f"using largest tier ({selected_tier.area_mm2}mm²)"
            )

        cable_tiers[(node_i, node_j)] = selected_tier
        logger.debug(
            f"[TIER] {node_i}→{node_j}: {selected_tier.area_mm2}mm² "
            f"({current_a:.1f}A, {d:.0f}m)"
        )

    return cable_tiers

def define_distance_matrix(nodes, names, dist_matrix):
    for a, b in itertools.permutations(names, 2):
        na = nodes[a]
        nb = nodes[b]
        d = geodesic_distance_m(
            na.lon,
            na.lat,
            nb.lon,
            nb.lat,
        )
        dist_matrix[(a, b)] = d
