import itertools
import logging
import os

from ortools.sat.python import cp_model

from nopywer import inventory
from nopywer.analyze import _compute_distro_requirements
from nopywer.constants import EXTRA_CABLE_LENGTH_M, PF, RHO_COPPER, V0, VDROP_THRESHOLD_PERCENT
from nopywer.geometry import geodesic_distance_m
from nopywer.models import _CABLE_TYPES, Cable, PowerGrid
from nopywer.optimization_tools import assign_phases_from_grid, segments_cross
from nopywer.optimize import _compute_power_flow

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
    datefmt="%m-%d %H:%M",
    filename="optimizer.log",
    filemode="w",
)
console = logging.StreamHandler()
console.setLevel(logging.INFO)
formatter = logging.Formatter("%(name)-12s: %(levelname)-8s %(message)s")
console.setFormatter(formatter)
logging.getLogger().addHandler(console)


MAX_POWER = 100000

# NOPYWER_INPUT='tests/fixtures/input_nodes.geojson'
# NOPYWER_OUTPUT='output.geojson'
# NOPYWER_INVENTORY='orange_inventory.xlsx'

INVENTORY = os.getenv("NOPYWER_INVENTORY", "orange_inventory.xlsx")

# TODO: add max number of connections for each distro/node

# basically, for any grid generated by the optim algo:
# you need to compute the voltage drop, current in each cables etc.
# So phases need to be assigned first. Then you check if the grid is valid
# then, only for those feasible solutions, you try to optimize voltage drop, total length, etc


def optimize_layout(
    grid: PowerGrid,
    extra_cable_m: float = EXTRA_CABLE_LENGTH_M,
) -> PowerGrid:

    ITERATE_ACCORDING_TO_INVENTORY = False
    nodes = grid.nodes
    node_names = list(nodes.keys())
    generator = grid.generator.name

    dist_matrix = {}
    define_distance_matrix(nodes, node_names, dist_matrix)

    model = cp_model.CpModel()

    connection_variables = define_connection_variables(node_names, model)
    flow = define_flow_variables(node_names, model)

    depth = {n: model.NewIntVar(0, len(node_names), f"depth_{n}") for n in node_names}
    model.Add(depth[generator] == 0)

    tier_variables = {}
    create_depth_constraint(node_names, model, connection_variables, depth)
    add_cable_tier_variables(node_names, model, tier_variables, nodes)
    tier_selection(node_names, model, connection_variables, tier_variables, nodes)
    add_cable_capacity_constraints(node_names, model, flow, tier_variables, nodes)
    add_flow_cable_exists_constraints(node_names, model, flow, tier_variables, nodes)
    add_no_crossing_constraints(node_names, nodes, model, connection_variables)
    add_nodes_proximity_constraints(node_names, nodes, model, connection_variables, dist_matrix)

    for n in nodes:
        if n == generator:
            continue
        model.Add(sum(connection_variables[(i, n)] for i in node_names if i != n) == 1)

    add_power_balance_constraints(nodes, node_names, generator, model, flow)

    generator_connections = [
        connection_variables[(generator, j)] for j in node_names if j != generator
    ]
    direct_connections_count = model.NewIntVar(0, len(node_names), "direct_connections")
    model.Add(direct_connections_count == sum(generator_connections))

    VOLTAGE_SCALE = 100
    RADIALITY_WEIGHT = 100000

    cost_terms = []
    cost_terms.append(direct_connections_count * RADIALITY_WEIGHT)

    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            if nodes[node_j].is_generator:  # never towards generator
                continue
            d = dist_matrix[(node_i, node_j)]

            # Select preferably smaller cable tiers
            for cable_type, tier in enumerate(_CABLE_TYPES):
                cost_terms.append(
                    int(d * tier.tier_cost * 100) * tier_variables[(node_i, node_j, cable_type)]
                )

            # Minimize voltage drop: flow * resistance <= Vdrop_threshold
            resistance_per_m = RHO_COPPER / tier.area_mm2
            rhs = int(VDROP_THRESHOLD_PERCENT / 100 * V0 * PF * VOLTAGE_SCALE)
            model.Add(
                flow[(node_i, node_j)] * int(resistance_per_m * d * VOLTAGE_SCALE) <= rhs
            ).OnlyEnforceIf(tier_variables[(node_i, node_j, cable_type)])

            # Penalize large direct connections from the gennie
            if nodes[node_i].is_generator:
                cost_terms.append(int(d * 20) * connection_variables[(node_i, node_j)])
            else:
            # Help minimize total length
                cost_terms.append(int(d * d / 1000) * connection_variables[(node_i, node_j)])

    model.Minimize(sum(cost_terms))
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = 120
    solver.parameters.log_search_progress = False
    solver.parameters.num_search_workers = 8
    solver.parameters.cp_model_presolve = True
    status = solver.Solve(model)

    if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            print("No solution found. Retrying with relaxed constraints...")
            raise RuntimeError("Optimization failed")

    _compute_distro_requirements(grid)
    grid = assign_nodes_and_cables(
        grid, extra_cable_m, nodes, node_names, dist_matrix, connection_variables, solver
    )

    while status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        if ITERATE_ACCORDING_TO_INVENTORY:
            # analyze_grid(grid, verbose=True)
            unmatched_cables = inventory.choose_cables(INVENTORY, grid.cables)
            # inventory.choose_distros(INVENTORY, grid.nodes)
            if unmatched_cables:
                for unm in unmatched_cables:
                    nodes = [unm.from_node, unm.to_node]
                    print(f"\t {unm.plugs_and_sockets_a}{'A':.<4}")
                    print(f"\t {unm.length_m:.0f}m) {'-'.join(nodes)}")
                print("Unmatched cables found in inventory, re-optimizing...")
                ITERATE_ACCORDING_TO_INVENTORY = True

                model.AddBoolOr(
                    [
                        connection_variables[(i, j)].Not()
                        if solver.Value(connection_variables[(i, j)]) == 1
                        else connection_variables[(i, j)]
                        for i in node_names
                        for j in node_names
                        if i != j
                    ]
                )
                status = solver.Solve(model)
            else:
                print("All cables matched with inventory. Optimization complete.")
                ITERATE_ACCORDING_TO_INVENTORY = False

        else:
            break

        total_cable_length_m = (
            round(
                sum(c.length_m for c in grid.cables.values()),
                1,
            ),
        )
        num_cables = len(grid.cables)
        logger.info(f"TOTAL DISTANCE: {total_cable_length_m}")
        logger.info(f"TOTAL CABLES: {num_cables}")

    return grid


def add_flow_cable_exists_constraints(node_names, model, flow, tier_variables, nodes):
    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            if nodes[node_j].is_generator:  # nunca hacia el generador
                continue
            model.Add(
                flow[(node_i, node_j)]
                <= sum(
                    tier.max_current_a * V0 * tier_variables[(node_i, node_j, t)]
                    for t, tier in enumerate(_CABLE_TYPES)
                )
            )


def add_nodes_proximity_constraints(node_names, nodes, model, connection_variables, dist_matrix):
    for node_i in node_names:
        for node_j in node_names:
            if node_i >= node_j:
                continue
            d_ij = dist_matrix[(node_i, node_j)]

            for node_k in node_names:
                if node_k == node_i or node_k == node_j:
                    continue
                # Si k está más lejos de ambos que i y j entre sí
                if dist_matrix[(node_k, node_i)] > d_ij and dist_matrix[(node_k, node_j)] > d_ij:
                    # No pueden ambos conectarse a k
                    model.Add(
                        connection_variables[(node_k, node_i)]
                        + connection_variables[(node_k, node_j)]
                        <= 1
                    )


def assign_nodes_and_cables(
    grid, extra_cable_m, nodes, node_names, dist_matrix, connection_variables, solver
):
    cid = 0
    cables: list[Cable] = []
    total_distance = []

    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue

            if solver.Value(connection_variables[(node_i, node_j)]):
                length = dist_matrix[(node_i, node_j)] + extra_cable_m
                total_distance.append(length)

                cable = Cable(
                    id=f"opt_{cid}",
                    length_m=length + extra_cable_m,
                    from_node=node_i,
                    to_node=node_j,
                    from_coords=(nodes[node_i].lon, nodes[node_i].lat),
                    to_coords=(nodes[node_j].lon, nodes[node_j].lat),
                )
                cables.append(cable)
                cid += 1

    computed_cables = _compute_power_flow(cables, nodes)
    node_phase, cable_phase, phase_loads = assign_phases_from_grid(nodes, computed_cables)
    for n in node_names:
        nodes[n].phase = node_phase.get(n, 0)
    grid.nodes = nodes

    for cable in computed_cables:
        cable.phase = cable_phase.get((cable.from_node, cable.to_node), 0)

    logger.info(f"[PHASE] phase loads: {phase_loads}")
    grid.phase_loads = phase_loads
    grid.cables = {cable.id: cable for cable in computed_cables}
    return grid


def add_no_crossing_constraints(node_names, nodes, model, connection_variables):
    crossing_pairs = 0
    for i, j, k, z in itertools.permutations(node_names, 4):
        if i >= k:  # prevents duplicates
            continue
        p1 = (nodes[i].lon, nodes[i].lat)
        p2 = (nodes[j].lon, nodes[j].lat)
        p3 = (nodes[k].lon, nodes[k].lat)
        p4 = (nodes[z].lon, nodes[z].lat)

        if segments_cross(p1, p2, p3, p4):
            # if these two edges cross, they can't both be in the solution
            model.Add(connection_variables[(i, j)] + connection_variables[(k, z)] <= 1)
            crossing_pairs += 1
    print(f"[CROSSING] pares de cruces prohibidos: {crossing_pairs}")


def create_depth_constraint(node_names, model, connection_v, depth):
    # depth -distance from generator - constraint to prevent cycles
    N = len(node_names)
    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            model.Add(depth[node_j] >= depth[node_i] + 1).OnlyEnforceIf(
                connection_v[(node_i, node_j)]
            )
            model.Add(depth[node_j] <= depth[node_i] + 1 + N * (1 - connection_v[(node_i, node_j)]))


def add_cable_capacity_constraints(node_names, model, flow, tier_variable, nodes):
    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            if nodes[node_j].is_generator:
                continue

            for cable_type, tier in enumerate(_CABLE_TYPES):
                model.Add(
                    flow[(node_i, node_j)] <= int(tier.max_current_a * V0 * PF)
                ).OnlyEnforceIf(tier_variable[(node_i, node_j, cable_type)])


def tier_selection(node_names, model, connection_v, tier_variable, nodes):
    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            if nodes[node_j].is_generator:
                continue
            model.Add(
                sum(tier_variable[(node_i, node_j, t)] for t in range(len(_CABLE_TYPES)))
                == connection_v[(node_i, node_j)]
            )


def define_flow_variables(node_names, model):
    flow = {}
    for node_i in node_names:
        for node_j in node_names:
            if node_i != node_j:
                flow[(node_i, node_j)] = model.NewIntVar(
                    0,
                    MAX_POWER,
                    f"flow_{node_i}_{node_j}",
                )

    return flow


def define_connection_variables(node_names, model):
    connection_v = {}
    for node_i in node_names:
        for node_j in node_names:
            if node_i != node_j:
                connection_v[(node_i, node_j)] = model.NewBoolVar(f"x_{node_i}_{node_j}")
    return connection_v


def add_power_balance_constraints(nodes, node_names, generator, model, flow):
    total_load = int(sum(n.power_watts for n in nodes.values() if not n.is_generator))
    for n in node_names:
        incoming = [flow[(i, n)] for i in node_names if i != n]
        outgoing = [flow[(n, j)] for j in node_names if j != n]
        if n == generator:
            model.Add(sum(outgoing) - sum(incoming) == total_load)
        else:
            model.Add(sum(incoming) - sum(outgoing) == int(nodes[n].power_watts))
    print("Total load:", total_load)


def add_cable_tier_variables(node_names, model, tier_variable, nodes):
    for node_i in node_names:
        for node_j in node_names:
            if node_i == node_j:
                continue
            if nodes[node_j].is_generator:  # never towards generator
                continue
            for cable_type in range(len(_CABLE_TYPES)):
                tier_variable[(node_i, node_j, cable_type)] = model.NewBoolVar(
                    f"tier_{cable_type}_{node_i}_{node_j}"
                )


def define_distance_matrix(nodes, names, dist_matrix):
    for a, b in itertools.permutations(names, 2):
        na = nodes[a]
        nb = nodes[b]
        d = geodesic_distance_m(
            na.lon,
            na.lat,
            nb.lon,
            nb.lat,
        )
        dist_matrix[(a, b)] = d
